"""These problems are from Project Euler (https://projecteuler.net/)
I strongly encourage you to visit the site to try and tackle a lot
of interesting mathematical/computational problems."""

###############################################################
# If we list all the natural numbers below 10 that are multiples 
# of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
#
# Find the sum of all the multiples of 3 or 5 below 1000.
###############################################################

def sum_multiples_3_5(num : int) -> int:
    list35 = []
    for i in range(num):
        if i % 3 == 0 or i % 5 == 0:
            list35.append(i)
    result = 0
    for i in list35:
        result += 1
    return result

print(sum_multiples_3_5(1000))

###############################################################
# Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. 
# By starting with 0 and 1, the first 10 terms will be:
# 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...
#
# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.
###############################################################

def sum_even_fibonacci_under(limit : int) -> int:
    sum = 0
    fibo = 1




###############################################################
# The sum of the squares of the first ten natural numbers is:
# 1^2 + 2^2 + ... + 10^2 = 385
# The square of the sum of the first ten natural numbers is:
# (1 + 2 + ... + 10)^2 = 55^2 = 3025
# Hence the difference between the sum of the squares of the 
# first ten natural numbers and the square of the sum is:
# 3025 - 385 = 2640.
# Find the difference between the sum of the squares of the 
# first one hundred natural numbers and the square of the sum.
###############################################################